### PR TITLE
Smarter path matching

### PR DESCRIPTION
**Pull request by makotom**

### CODE REVIEW

**Comment by makotom** [comment]
Hei @tjokimie -

WRT #4 I've staged `circle-makotom-orbs/config-splitting@dev:0.0.7` with this patch applied. Could you help me test the patch by checking whether the developer version fixes the issue without noticeable regression? I really appreciate your contribution!

**Comment by tjokimie** [comment]
Hei @makotom!

I verified that the patch you provided works [here](https://github.com/tjokimie/config-splitting-bug/pull/3). I also bumped the version in our private monorepo. We'll use it for a day or two and I'll report back to you how it works 👌 

Thank you so much for the patch!

**Comment by tjokimie** [comment]
@makotom We tested the patch with our private monorepo and it seems to work well there too! 🎉

**Comment by makotom** [comment]
Thanks @tjokimie for confirmation! I've merged the change and published `circle-makotom-orbs/config-splitting@0.0.8`. Thank you very much for your contribution!

**Comment by tjokimie** [comment]
Kiitos paljon! ❤️

**Pull request merged**
